version: "3.8"

services:
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com  # อีเมลสำหรับเข้าสู่ระบบ pgAdmin
          PGADMIN_DEFAULT_PASSWORD: password           # รหัสผ่านสำหรับเข้าสู่ระบบ pgAdmin
        ports:
          - "15432:80"  # ผูกพอร์ตสำหรับ pgAdmin
        networks:
          - local_network   # กำหนด network ที่จะใช้

networks:
  local_network:
    external: true 