version: "3.8"

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432    
        volumes:
            - ./postgres:/var/lib/postgresql
        networks:
          - local_network   # กำหนด network ที่จะใช้
volumes:
    postgres:

networks:
  local_network:
    external: true 

