FROM phpmyadmin/phpmyadmin

RUN echo "upload_max_filesize=1G" > /usr/local/etc/php/conf.d/uploads.ini
RUN echo "post_max_size=1G" >> /usr/local/etc/php/conf.d/uploads.ini
RUN echo "memory_limit=1G" >> /usr/local/etc/php/conf.d/uploads.ini
