version: '3'
services:
  nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
          - ./conf:/etc/nginx/conf.d
        ports:
          - 80:80
          - 443:443
        deploy:
          resources:
            limits:
              cpus: "4.0"
              memory: 200M
