version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "6101:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - db_default

networks:
  db_default:
    external: true